import * as THREE from 'three';
import type {World} from '../../shared/game-types/index.ts';
export class HazardView{
 private root=new THREE.Group();private rocks=new Map<string,THREE.Group>();private wind=new THREE.Group();
 private circle=new THREE.RingGeometry(1.42,1.6,40);private disk=new THREE.CircleGeometry(1.42,40);private stone=new THREE.DodecahedronGeometry(.9);private stoneMat=new THREE.MeshStandardMaterial({color:0x73899c,roughness:.95});private danger=new THREE.MeshBasicMaterial({color:0xf45851,side:THREE.DoubleSide});private fill=new THREE.MeshBasicMaterial({color:0xf45851,transparent:true,opacity:.2,side:THREE.DoubleSide,depthWrite:false});private arrowMat=new THREE.MeshBasicMaterial({color:0xb8f4ff,transparent:true,opacity:.8,side:THREE.DoubleSide,depthWrite:false});
 constructor(scene:THREE.Scene){scene.add(this.root);this.root.add(this.wind);const shape=new THREE.Shape();shape.moveTo(-.13,-.7);shape.lineTo(.13,-.7);shape.lineTo(.13,.15);shape.lineTo(.45,.15);shape.lineTo(0,.7);shape.lineTo(-.45,.15);shape.lineTo(-.13,.15);shape.closePath();const geometry=new THREE.ShapeGeometry(shape);geometry.rotateX(Math.PI/2);const arrows=new THREE.InstancedMesh(geometry,this.arrowMat,25),matrix=new THREE.Matrix4();arrows.count=0;for(let x=-6;x<=6;x+=3)for(let z=-6;z<=6;z+=3){if(Math.hypot(x,z)>8)continue;arrows.setMatrixAt(arrows.count++,matrix.makeTranslation(x,.08,z));}arrows.instanceMatrix.needsUpdate=true;arrows.computeBoundingSphere();this.wind.add(arrows);}
 update(w:World,lobby:boolean,reduced:boolean){this.root.visible=!lobby;const ids=new Set<string>();
  for(const rock of w.hazards?.rocks??[]){ids.add(rock.id);let group=this.rocks.get(rock.id);if(!group){group=new THREE.Group();const ring=new THREE.Mesh(this.circle,this.danger),disk=new THREE.Mesh(this.disk,this.fill);ring.rotation.x=disk.rotation.x=-Math.PI/2;ring.position.y=.04;disk.position.y=.03;group.add(ring,disk,new THREE.Mesh(this.stone,this.stoneMat));this.rocks.set(rock.id,group);this.root.add(group);}group.position.set(rock.x,0,rock.z);const left=rock.at-w.activeTick;group.children[0].visible=group.children[1].visible=left>=0;group.children[2].position.y=left>0?1+Math.pow(left/30,2)*12:Math.max(.2,1+(left*.05)*3);group.children[2].visible=!reduced||left<=0;group.children[2].rotation.z=reduced?0:w.activeTick*.07;}
  for(const [id,group]of this.rocks)if(!ids.has(id)){this.root.remove(group);this.rocks.delete(id);}
  const gust=w.hazards?.gust;this.wind.visible=!!gust;if(gust){this.wind.rotation.y=Math.atan2(gust.dx,gust.dz);this.arrowMat.color.setHex(w.activeTick<gust.startAt?0x236780:0x3096b2);this.arrowMat.opacity=reduced?.9:.85+Math.sin(w.activeTick*.4)*.1;this.wind.position.y=w.activeTick<gust.startAt?0:.2;}
 }
}

